### ISSUE TITLE
support for stylus?

### ISSUE THREAD

**Issue by adamwong246** [lookback/meteor-emails#10]
any possibility of support for stylus, as opposed to scss?

**Comment by jadsonlourenco** [comment]
Yes! And just install SCSS package if use it.

**Comment by johanbrook** [comment]
@adamwong246 Guess that would be possible. 

@jadsonlourenco How do you mean?

**Comment by jadsonlourenco** [comment]
@johanbrook Sorry, I explain better my case: in this line https://github.com/lookback/meteor-emails/blob/master/package.js#L11 you use "Node-sass" to compile the SCSS/SASS files for CSS, that is fine, BUT when I compile the App to "bundle" (NodeJS version) and try start it on Linux I get an error, this error is related to Node-sass, not your package, so if you get an way to not install Node-sass if don't use it, like an option to use just CSS, not will get more problems because of that.

In my case I remove the SCSS code of this package and use as local package to not fight with Node-sass.

Thanks!

**Comment by johanbrook** [comment]
@jadsonlourenco I've now removed `node-sass` as a hard dependency in here: https://github.com/lookback/meteor-emails/pull/35. Feel free to pull down and test.

**Comment by jadsonlourenco** [comment]
@johanbrook Ok man, I will test this now, thanks!!

**Comment by johanbrook** [comment]
Since I ripped out `node-sass` as a hard dependency, anyone is welcome to write a PR for stylus support.
