### ISSUE TITLE
Missing attachment parameter documentation

### ISSUE THREAD

**Issue by opyh** [lookback/meteor-emails#69]
Hi,

the documentation link for how to specify attachments seems to point to an API that is different from the actually working attachment API.

Using the documented API results in missing attachments (there should be an error message for attachments that are not correctly specified, but there isn't. Always sanitize your input arguments! :) )

This is _working_ for me:

```
attachments: [{
  fileName: "my-file.jpg",
  filePath: 'https://s3…/my-file.jpg',
  contentType: 'jpg'
}]
```

_Not_ working for me:

```
attachments: [{
  filename: 'license.txt',
  path: 'https://raw.github.com/andris9/Nodemailer/master/LICENSE'
}],
```

Note the different case `fileName` vs. `filename` and `filePath` vs. `path` here.

I couldn't find out when the API exactly changed, but did this write-up so hopefully it helps somebody who needs to get attachments working with meteor-emails.

Thanks for your otherwise awesome package!

**Comment by johanbrook** [comment]
Hi there!

Thanks for reporting in. What a mess, the official Meteor docs points to this: https://github.com/nodemailer/mailcomposer/blob/7c0422b2de2dc61a60ba27cfa3353472f662aeb5/README.md#add-attachments which is inconsistent with the main, `master` README in the MailComposer repo .. The options described in the link matches the ones in your successful test above.

Since I pass this option on to Meteor's `Email` module, I feel it's not up to this package to validate the keys inside of an `attachment` array. But I'll update the README with the correct info.

**Comment by johanbrook** [comment]
Added docs in https://github.com/lookback/meteor-emails/commit/69d6b0e0836cf236517377402203bafbd27a42cc.

**Comment by opyh** [comment]
The sanitizing reminder was a general thing and not directed at you ;) Thanks for your effort!

**Comment by johanbrook** [comment]
No worries! Do the changes in the commit above work well now, you think?

**Comment by opyh** [comment]
Yes! :+1:

**Comment by johanbrook** [comment]
Sweet! Thanks again.
